---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nexusatn/justice-data.com/coding/
    - /bin/cp -R . $DEPLOYPATH
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - php artisan migrate --force