---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dcjmigra/public_html/dcj/
    - /bin/cp -R . $DEPLOYPATH
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - php artisan migrate --force